default:
  outputs:
    dev:
      type: duckdb
      path: "../data/local.duckdb"
      threads: 8
      external_root: "../data"
  target: dev

config:
  send_anonymous_usage_stats: False
  use_colors: True
