version: 2

models:


  - name : gitcoin_passport_scores
    columns:
      - name: address
        tests: ['is_address_lowercase']

  - name: allo_projects
    columns:
      - name: chain_id
        tests: ['not_null']

  - name : allo_applications
    columns:
      - name: metadata_application_recipient
        tests: ['is_address_lowercase']

  - name : allo_donations
    columns:
      - name: donor_address
        tests: ['not_null', 'is_address_lowercase']
      - name: recipient_address
        tests: ['not_null','is_address_lowercase']
      - name: token_address
        tests: ['is_address_lowercase']

  - name : allo_rounds
    columns:
      - name: round_metadata_program_address
        tests: ['is_address_lowercase']
      - name: id
        tests: ['is_address_lowercase']
