project:
  type: website

website:
  title: "Gitcoin Grants Data Portal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: notebook.ipynb
        text: Notebook
      - href: catalog.ipynb
        text: Catalog
      - href: dbt
        text: dbt Docs

format:
  html:
    theme:
      - Lumen
      - styles.scss
