project:
  type: website

website:
  title: "Gitcoin Grants Data Portal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: sandbox.ipynb
        text: Sandbox

format:
  html:
    theme:
      - Lumen
      - styles.scss
