name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker
      run: docker build -t davidgasquez/ggdp:latest .

    - name: Run Make
      run: docker run --rm -v $PWD/:/workspaces/gitcoin-grants-data-portal/ davidgasquez/ggdp:latest make run

    - name: Publish Web
      run: docker run --rm -v $PWD/:/workspaces/gitcoin-grants-data-portal/ davidgasquez/ggdp:latest sh -c 'quarto render reports/sandbox.ipynb -o index.html && mv index.html reports/sandbox_files/ data/'

    - name: "Set current date as env variable"
      id: version
      run: |
        echo "tag_name=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create-release
      uses: shogo82148/actions-create-release@v1
      with:
        draft: true
        release_name: ${{ steps.version.outputs.tag_name }}
        tag_name: ${{ steps.version.outputs.tag_name }}
        commitish: ${{ github.sha }}

    - name: Upload Assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/data/dbt.duckdb
        asset_name: dbt.duckdb

    - name: Upload to IPFS
      uses: web3-storage/add-to-web3@v2
      id: web3
      with:
        web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
        path_to_add: 'data'

    - run: echo ${{ steps.web3.outputs.cid }}
    - run: echo ${{ steps.web3.outputs.url }}

    - name: Publish release
      uses: StuYarrow/publish-release@v1.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        id: ${{ steps.create-release.outputs.id }}
