name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: pip

    - name: Install dependencies
      run: |
        pip install -e .

    - name: Run
      id: run_make
      run: |
        make run
        echo "::set-output name=exit_code::$?"

    - name: Export Database and Log File Sizes
      run: |
        python -c 'from ggdp import db; db.export_database_to_parquet("data/local.duckdb", "tables");'
        echo "Files exported:" >> $GITHUB_STEP_SUMMARY
        {
          echo "| Filename | File Size |"
          echo "| --- | --- |"
          ls -lh tables | tail -n +2 | awk '{printf "| %s | %s |\n", $9, $5}'
        } >> $GITHUB_STEP_SUMMARY
        ls -lh tables

    - name: Fail Job if Make Fails
      run: |
          if [ "${{ steps.run_make.outputs.exit_code }}" != "0" ]; then
            echo "make run failed with exit code ${{ steps.run_make.outputs.exit_code }}"
            exit 1
          fi       