name: CI

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: pip

    - name: Install dependencies
      run: |
        pip install -e .
    - name: Run
      run: |
        dagster asset materialize -f ./ggdp/assets.py --select raw_rounds 2>&1 | tee output.log
        
    - name: Parse Dagster logs and append to GitHub Job Summary
      run: |
        echo "| Asset Name | Message |" >> $GITHUB_STEP_SUMMARY
        echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
        grep "ASSET" output.log | while IFS= read -r line; do
          parsed_line=$(echo "$line" | awk -F ' - ' '{printf "| %s | %s |", $7, $8}')
          echo "$parsed_line" >> $GITHUB_STEP_SUMMARY
        done
    
