name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: pip

    - name: Install dependencies
      run: |
        pip install -e .

    - name: Run
      run: |
        make run 2>&1 | tee output.log

    - name: Parse Dagster logs and append to GitHub Job Summary
      run: |
        echo "| Timestamp | Table Name | Status | Message |" >> $GITHUB_STEP_SUMMARY
        echo "| --- | --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
        grep "STEP_FAILURE" output.log | while IFS= read -r line; do
          parsed_line=$(echo "$line" | awk -F ' - ' '{printf "| %s | %s | %s | %s |", $1, $7, $8, $9}')
          echo "$parsed_line" >> $GITHUB_STEP_SUMMARY
        done
        if ! grep -q "STEP_FAILURE" output.log; then
          echo "| | | | |" >> $GITHUB_STEP_SUMMARY
        fi
    
    - name: Export Database and Log File Sizes
      run: |
        python -c 'from ggdp import db; db.export_database_to_parquet("data/local.duckdb", "tables");'
        {
          echo "| File Size | Filename |"
          echo "| --- | --- |"
          ls -lh tables | tail -n +2 | awk '{printf "| %s | %s |\n", $5, $9}'
        } | tee -a $GITHUB_STEP_SUMMARY

