name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: pip

    - name: Install dependencies
      run: |
        pip install -e .

    - name: Run
      run: |
        make run 2>&1 | tee output.log


    
    - name: Export Database and Log File Sizes
      run: |
        python -c 'from ggdp import db; db.export_database_to_parquet("data/local.duckdb", "tables");'
        echo "Files exported:" >> $GITHUB_STEP_SUMMARY
        {
          echo "| Filename | File Size |"
          echo "| --- | --- |"
          ls -lh tables | tail -n +2 | awk '{printf "| %s | %s |\n", $9, $5}'
        } >> $GITHUB_STEP_SUMMARY
        echo "Files exported:"
        ls -lh tables

