name: Check Links

on: 
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        id: link-report
        uses: elliotforbes/broken-link-checker@1.0.2
        with:
          url: "https://davidgasquez.github.io/gitcoin-grants-data-portal/"
          cmd_params: "--exclude=google.com --buffer-size=8192 --max-connections=10 --color=always --verbose"
